title: open-co.de
description: Open Source - made in Germany  
theme: minima
header_pages:
  - portfolio.md
  - links.md 
  - about.md

email: info@open-co.de
author: Markus Tiede

twitter_username: OpenCo_de
github_username:  open-co-de

google_analytics: UA-120597361-1
